# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentMap',
            fields=[
                ('mapName', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('no_of_ques', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('hint', models.CharField(max_length=1000)),
                ('ques_no', models.IntegerField()),
                ('tags', models.CharField(max_length=1000)),
                ('maps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids_app.ParentMap', verbose_name='mapName')),
            ],
        ),
    ]
